import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from '@radix-ui/themes';
import NavBar from './NavBar';
import purpleBlueBg from '@/public/images/purpleBlueBg.png';
import AnimatedBackground from './components/AnimatedBackground';
import x5 from '@/public/images/x5.png'
import FooterArea from './components/FooterArea';
import AllPageContainer from './components/AllPageContainer';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SoilX',
  description: 'Generated by create next app',
  icons: '/public/images/X5.png'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <Theme
          accentColor="iris"
          radius="large"
        >
          <AnimatedBackground />
          <NavBar />
          <AllPageContainer>
            {children}
          </AllPageContainer>
          {/* <ThemePanel /> */}
          <FooterArea />
        </Theme>
      </body>
    </html>
  )
}
